### ISSUE TITLE
How to configure the full eco-system on mac

### ISSUE THREAD

**Issue by archanpatkar** [cloudOver/corecluster#55]
I was trying and I installed core cluster through pip but I wanted to know what to do next ?

**Comment by cloudOver** [comment]
Hi,
coreCluster is dedicated for Linux distributions - the base library (Libvirt) doesn't support Mac OS in hypervisor mode.

However you can try to start it inside virtual machine with Ubuntu or Debian. Alternatively, try to download sbin/cc-admin from repo and run only API:
cc-admin runserver 0.0.0.0:8000

**Comment by archanpatkar** [comment]
Thank you
